/*
* generated by Xtext
*/
package com.opcoach.restaurant.menu.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MenuDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.opcoach.restaurant.menu.xtext.ui.internal.MenuDslActivator.getInstance().getInjector("com.opcoach.restaurant.menu.xtext.MenuDsl");
	}
	
}
