/**
 * generated by Xtext
 */
package com.opcoach.restaurant.menu.xtext.ui.contentassist;

import com.opcoach.restaurant.menu.xtext.ui.contentassist.AbstractMenuDslProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class MenuDslProposalProvider extends AbstractMenuDslProposalProvider {
}
