<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="menu" nsURI="http://www.opcoach.com/restaurant/menu/1.0" nsPrefix="menu">
  <eClassifiers xsi:type="ecore:EClass" name="Menu">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groups" upperBound="-1"
        eType="#//Group" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Group">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="#//Category"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recipes" upperBound="-1"
        eType="#//Recipe" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Recipe">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amountType" eType="#//AmountType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ingredients" upperBound="-1"
        eType="#//Ingredient" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ingredient">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="spiciness" eType="#//Spiciness"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Spiciness">
    <eLiterals name="VeryHot" literal="Very hot"/>
    <eLiterals name="Hot" value="1" literal="Hot"/>
    <eLiterals name="Normal" value="2" literal="Normal"/>
    <eLiterals name="Mild" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AmountType">
    <eLiterals name="gram"/>
    <eLiterals name="milliliters" value="1"/>
    <eLiterals name="bottles" value="2"/>
    <eLiterals name="items" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Category">
    <eLiterals name="breakfast"/>
    <eLiterals name="dinner" value="1"/>
    <eLiterals name="lunch" value="2"/>
    <eLiterals name="supper" value="3"/>
    <eLiterals name="dessert" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DishType">
    <eLiterals name="pork"/>
    <eLiterals name="poultry" value="1"/>
    <eLiterals name="beef" value="2"/>
    <eLiterals name="fish" value="3"/>
    <eLiterals name="salad" value="4"/>
  </eClassifiers>
</ecore:EPackage>
