/*
 * generated by Xtext
 */
package com.opcoach.restaurant.menu.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MenuDslUiModule extends com.opcoach.restaurant.menu.xtext.ui.AbstractMenuDslUiModule {
	public MenuDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
