/**
 * generated by Xtext
 */
package com.opcoach.restaurant.menu.xtext.serializer;

import com.opcoach.restaurant.menu.xtext.serializer.AbstractMenuDslSyntacticSequencer;

@SuppressWarnings("all")
public class MenuDslSyntacticSequencer extends AbstractMenuDslSyntacticSequencer {
}
