/**
 * generated by Xtext
 */
package com.opcoach.restaurant.menu.xtext.serializer;

import com.opcoach.restaurant.menu.xtext.serializer.AbstractMenuDslSemanticSequencer;

@SuppressWarnings("all")
public class MenuDslSemanticSequencer extends AbstractMenuDslSemanticSequencer {
}
