/*
 * generated by Xtext
 */
package com.opcoach.restaurant.menu.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.opcoach.restaurant.menu.xtext.ui.internal.MenuDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MenuDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MenuDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MenuDslActivator.getInstance().getInjector(MenuDslActivator.COM_OPCOACH_RESTAURANT_MENU_XTEXT_MENUDSL);
	}
	
}
