<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="restaurant" nsURI="http://www.opcoach.com/restaurant/1.0" nsPrefix="re">
  <eClassifiers xsi:type="ecore:EClass" name="Restaurant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="menus" upperBound="-1"
        eType="ecore:EClass ../../com.opcoach.restaurant.menu/model/menu.ecore#//Menu"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tables" upperBound="-1"
        eType="#//Table" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="waiters" upperBound="-1"
        eType="#//Waiter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bookings" upperBound="-1"
        eType="#//Booking" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Table"/>
  <eClassifiers xsi:type="ecore:EClass" name="Waiter"/>
  <eClassifiers xsi:type="ecore:EClass" name="Booking"/>
</ecore:EPackage>
