/*
* generated by Xtext
*/
package com.opcoach.restaurant.menu.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MenuDslStandaloneSetup extends MenuDslStandaloneSetupGenerated{

	public static void doSetup() {
		new MenuDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

