/*
 * generated by Xtext
 */
package com.opcoach.restaurant.menu.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MenuDslRuntimeModule extends com.opcoach.restaurant.menu.xtext.AbstractMenuDslRuntimeModule {

}
