/**
 * generated by Xtext
 */
package com.opcoach.restaurant.menu.xtext.validation;

import com.opcoach.restaurant.menu.xtext.validation.AbstractMenuDslValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class MenuDslValidator extends AbstractMenuDslValidator {
}
