/*
* generated by Xtext
*/
package com.opcoach.restaurant.menu.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MenuDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/opcoach/restaurant/menu/xtext/parser/antlr/internal/InternalMenuDsl.tokens");
	}
}
