/*
* generated by Xtext
*/
package com.opcoach.restaurant.menu.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.opcoach.restaurant.menu.xtext.services.MenuDslGrammarAccess;

public class MenuDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MenuDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.opcoach.restaurant.menu.xtext.parser.antlr.internal.InternalMenuDslParser createParser(XtextTokenStream stream) {
		return new com.opcoach.restaurant.menu.xtext.parser.antlr.internal.InternalMenuDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Group";
	}
	
	public MenuDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MenuDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
